# -*- coding: utf-8 -*-
"""linkedinData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQFod8fg7der8rTdV_BlNZwDtN7EHCpA
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_excel('company_dtasheet.xlsx')
df.head(10)

df.shape

df.info()

df.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

df.shape

df.describe()

df['Company Name'].value_counts()

df['Company Specialization'].value_counts()

plt.figure(figsize = (140,6))
sns.countplot(x = 'Company Name',
              data = df,
              order = df['Company Name'].value_counts().index)

plt.figure(figsize = (60,7))
sns.countplot(x = 'Company Specialization',
              data = df,
              order = df['Company Specialization'].value_counts().index)